# JDBC
spring:
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/ruoxi?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: admin
    password: feihua
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.0.100
    port: 6379
    password: feihua

# server
server:
  port: 8082
# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    root: error
    org.springframework.web: error
    org.springframework.security: error
management:
  endpoints:
    web:
      exposure:
        include: '*'
